extends: spectral:oas

rules:
  operation-description:
    description: Every operation should have a non-empty description.
    severity: error
    given: "$.paths[*][*]"
    then:
      field: description
      function: truthy

  opration-id:
    description: Every operation should have operation-id. 
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: operationId
      function: truthy
    

